SHTOOLS/SHTOOLS

- examples/python/GlobalSpectralAnalysis/SHComplexSpectralAnalysis.py
- examples/python/GlobalSpectralAnalysis/SHRealSpectralAnalysis.py
- examples/python/IOStorageConversions/SHConversions.py
- examples/python/IOStorageConversions/SHStorage.py
- examples/python/LocalizedSpectralAnalysis/SHMultitaperSE.py
- examples/python/SHRotations/SHRotations.py
- examples/python/TimingAccuracy/TimingAccuracyDH.py
- examples/python/TimingAccuracy/TimingAccuracyDHC.py
- examples/python/TimingAccuracy/TimingAccuracyGLQ.py
- examples/python/TimingAccuracy/TimingAccuracyGLQC.py
- pyshtools/README
- pyshtools/classes.py
It just adds clutter when you need to specify the shape twice like these cases.
~~This is based on #17, so there are _lots_ of extra changes, but they would conflict if I sent them separately. I'll rebase when those are merged.~~
> Remove unnecessary array reshaping. 

- src/EigValSym.f95
- src/EigValSym2.f95
- src/EigValVecSym.f95
- src/EigValVecSym2.f95
- src/EigValVecSymTri.f95
- src/EigValVecSymTri2.f95
- src/MakeGravGradGridDH.f95
- src/MakeGravGradGridDH2.f95
- src/MakeGridDHC2.f95
- src/Makefile
- src/SHExpandDH2.f95
- src/SHExpandLSQ.f95
- src/SHExpandLSQ2.f95
- src/SHMTDebias.f95
- src/SHMTDebias2.f95
- src/SHMTVarOpt.f95
- src/SHMTVarOpt2.f95
The duplicate files for different underscore conventions were slightly out of sync with each other.
I still think it is best to get rid of these duplicate files entirely, but I'll leave that for after these PRs are accepted.
> Dupe consistency

- pyshtools/__init__.py
- pyshtools/make_docs.py
- src/create_signature.py
- src/create_wrapper.py
This prevents them from not being closed if an exception is raised.
> Use context manager to open files.

- setup.py
This works as usual compiling process, but directly from setup.py
Note: I use Arch Linux and there f2py command is for python3 and f2py2 is for python2, as well as python is for python3, not python2. So, in my case I still need to modify Makefile before compiling.
> Add make fortran && make python in setup.py

- .travis.yml
- examples/python/GlobalSpectralAnalysis/SHRealSpectralAnalysis.py
- examples/python/TimingAccuracy/TimingAccuracyDH.py
- examples/python/TimingAccuracy/TimingAccuracyDHC.py
- examples/python/TimingAccuracy/TimingAccuracyGLQ.py
- examples/python/TimingAccuracy/TimingAccuracyGLQC.py
- setup.py
linux build works, max build doesn't. I'll leave the mac commands to @MarkWieczorek , in particular how to install lapack / fftw etc... It is not complicated to change in the .travis.yml
For the moment, only the installation and one Timing test is executed on travis. I think before running all tests, we should probably restructure them according to the python standard, and maybe run the fortran tests independently.
> travis support

- examples/notebooks/Introduction-1.ipynb
- examples/notebooks/Introduction-2.ipynb
some very small corrections ...
> small corrections to the notebooks

- .travis.yml
- README_DEVELOPMENT.md
- VERSION
- setup.py
travis compiles the notebooks as test. This is just a preliminary test method.
> run notebooks on travis

- pyshtools/shclasses.py
return_coeffs returns copy by default. First part of #50
> return_coeffs returns copy by default

- setup.py
This PR automatically sets the required numpy version to that which shtools is compiled against.
> [setup] autoset numpy version

- README.md
- VERSION
- docs/pages/mydoc/installing.md
- src/SHExpandLSQ.F95
Final commit before new release.
> Update README, VERSION, and minor tweaks for next release.

- pyshtools/expand/spharm_functions.py
I think this might make it a bit clearer to understand. If this is not acceptable, feel free to close this PR.
Thanks!
> Clarify docs in spharm_functions.py

- src/PlBar_d1.f95
- src/PlON_d1.f95
This pull request fixes bugs in the Fortran code of `PlBar_d1` and `PlON_d1` when calculating Pl(1.0) and Pl(-1.0).
#210
> Fix bugs in PlBar_d1 and PlON_d1

- pyshtools/shclasses/shcoeffsgrid.py
For simplicity I just reopened PR #213 .
Only 1 file changed, there should be no problems with merging anymore.
Best,
Stefan
> Add netcdf io to shcoeffsgrid.py

- MANIFEST.in
- docs/pages/mydoc/release-notes-v4.md
- setup.py
> Version 4.6.1

- .gitlab-ci.yml
- .travis.yml
- binder/environment.yml
- docs/.gitlab-ci.yml
- docs/pages/mydoc/python-shgrid.md
- environment.yml
- pyshtools/shclasses/shgrid.py
- requirements-dev.txt
- requirements.txt
* Add option empty to SHGrid.from_zeros() in order to return an empty data array that is not initialized to zero.
> SHGrid.from_ellipsoid()

- .github/workflows/ci_test.yml
- .github/workflows/pypi_publish.yml
- docs/index.md
> Update github CI workflow for macOS

- src/cWrapper.f95
> Add C wrapper for MakeGradientDH

- docs/index.md
- docs/pages/fortran/fortran-release-notes-v4.md
- docs/pages/mydoc/backends.md
- docs/pages/mydoc/python-installing.md
- docs/pages/mydoc/release-notes-v4.md
> Use a better URL when referring to ducc

- pyshtools/backends/ducc0_wrapper.py
> convert input arrays if necessary

- pyshtools/backends/backends.py
This keeps track of the available backends in a dictionary, which allows removing a lot of redundant code.
**Reminders**
> Simplify backend management

- .github/workflows/ci_test.yml
- .github/workflows/pypi_publish.yml
- docs/pages/fortran/fortran-release-notes-v4.md
- docs/pages/mydoc/python-datasets-constants.md
- docs/pages/mydoc/release-notes-v4.md
- environment-dev.yml
- pyshtools/datasets/Mars/__init__.py
- setup.py
* Fix setup.py to work with setuptools 62.1.0
* Add MarsTopo719 dataset for use in CI checks (using MarsTopo2600 often would timeout during download).
**Reminders**
> Tweak workflow and pin setuptools=62.0.0 since 62.1.0 is broken

- .github/ISSUE_TEMPLATE/release_checklist.md
- .github/workflows/pypi_publish.yml
- Makefile
- README.md
- docs/_config.yml
- docs/_data/sidebars/fortran_sidebar.yml
- docs/_data/sidebars/mydoc_sidebar.yml
- docs/_includes/footer.html
- docs/index.md
- docs/pages/fortran/fdoc/shtools.md
- docs/pages/fortran/index-fortran.md
- man/man1/shtools.1
- pyshtools/__init__.py
- pyshtools/gravmag/mag_spectrum.py
- pyshtools/shclasses/shgravgrid.py
- pyshtools/shclasses/shmagcoeffs.py
- pyshtools/shclasses/shmaggrid.py
- pyshtools/shclasses/shtensor.py
- src/Makefile
- src/fdoc/shtools.md
* Update handling of the project version number "4.10" in the web documentations, which was previously treated as an integer.
* remove "-static" option from compiler options.
* Update version numbers of packages used in workflow.
* convert some strings to raw format when they contain latex backslashes.
> minor changes for 4.10.1

- docs/pages/fortran/fortran-release-notes-v4.md
- docs/pages/mydoc/release-notes-v4.md
> update release notes

- pyshtools/__init__.py
This breaks the circular import reported in #401 
**Reminders**
> Break circular imports. #401

- .github/workflows/ci_test.yml
- AUTHORS.md
- docs/pages/fortran/fortran-contributors.md
- docs/pages/mydoc/contributors.md
- pyshtools/__init__.py
* Update Authors
* Remove deprecated `pyshtools.shtools` top level module.
* Replace `mamba` by `conda` for some commands in the CI workflow to get around a mamba bug.
> various fixes

- .github/workflows/pypi_publish.yml
fix actions/checkout to get tags
> update release workflow

- .github/workflows/pypi_publish.yml
update release workflow for new pypi authentification
**Reminders**
> update release workflow for pypi authentification

- pyproject.toml
> update release workflow to not run tests

- docs/pages/mydoc/python-datasets.md
- docs/pages/mydoc/python-installing.md
- pyshtools/constants/Callisto.py
- pyshtools/constants/Ceres.py
- pyshtools/constants/Charon.py
- pyshtools/constants/Enceladus.py
- pyshtools/constants/Eros.py
- pyshtools/constants/Europa.py
- pyshtools/constants/Ganymede.py
- pyshtools/constants/Io.py
- pyshtools/constants/Mars.py
- pyshtools/constants/Mercury.py
- pyshtools/constants/Moon.py
- pyshtools/constants/Pluto.py
- pyshtools/constants/Psyche.py
- pyshtools/constants/Titan.py
- pyshtools/constants/Venus.py
- pyshtools/constants/Vesta.py
- pyshtools/constants/__init__.py
- pyshtools/constants/meson.build
- pyshtools/datasets/Psyche.py
- pyshtools/datasets/__init__.py
- pyshtools/datasets/meson.build
* Add a new shape model of the asteroid 16 Psyche derived from Shepard et al. (2021).
* Add a new constants module for the asteroid Psyche.
> Psyche datasets and constants

- .github/ISSUE_TEMPLATE/release_checklist.md
- binder/environment.yml
- docs/pages/mydoc/python-datasets.md
> Minor web doc and binder changes

- docs/pages/mydoc/python-installing.md
- environment.yml
- requirements.txt
* Use astropy-base instead of astropy.
> Change astropy packages to astropy-base
