SHTOOLS/SHTOOLS

setup.py

I created a simple setup.py script which can be used instead of 
`make install-python2` or  `make install-python3`
if you want to install only pyshtools without Fortran library.
It works with both python 2 and 3, supports `pip` command.
The main issues:
1. It works only after usual compilation with `make fortran && make python` commands. 
2.  The script contains `get_version()` function for unique (release number from VERSION file + 0.1 + .dev0 + git revision) versioning through development stage with PEP440 support. Other convention, of course, can be made.
3. It's recommended to put `author_email` key in `setup()`
The next stage is to include f2py compilation routines in setup.py. It is not so difficult, except putting documentation from `make_docs.py` to the final package. I really got …

Simple setup.py script

---

setup.py

1. All Fortran sources can be compiled from setup.py. 
Funny that `numpy.distutils.fcompiler.FCompiler` doesn't support `.F95` extension. It took me a few hours to find this.
2. The setup.py automatically detects your compiler and sets required  flags.
4. I don't think we need to check `numpy` in the import section, because we already set `install_requires`. Also, I removed `setuptools`, because it is not needed anymore (or for now).

Add full Fortran compilation support in setup.py and some refactoring

---

pyshtools/__init__.py
pyshtools/constant.py
pyshtools/expand.py
pyshtools/gravmag.py
pyshtools/legendre.py
pyshtools/localizedspectralanalysis.py
pyshtools/make_docs.py
pyshtools/other.py
pyshtools/rotate.py
pyshtools/shclasses.py
pyshtools/shio.py
pyshtools/spectralanalysis.py
www/using-python.html

I've removed most future imports that are not necessary. The only exceptions are a few import print_function when print is explicitly used.
One problem I would like to fix is the import _SHTOOLS statement in make_docs, as this is not a relative import. I tried the following but it doesn't work:
In the make file, I ran this as a module using "-m"
~~~~
$(PYTHON) -m ./pyshtools/make_docs.py . .
~~~~
and in make_docs.py I used
~~~~
from . import _SHTOOLS
~~~~
but then I get the error when building:
~~~~
python -m ./pyshtools/make_docs.py . . 
/usr/local/opt/python/bin/python2.7: Relative module names not supported
~~~~

Remove future imports from most pyshtools files.

---

README.md

installation instructions are cleaner now. On OSX, installation should be done with ```pip install .``` as well, right?

cleaner installation instructions

---

src/MakeCircleCoord.f95
src/MakeEllipseCoord.f95
src/MakeGeoidGrid.f95
src/MakeGrid2D.f95
src/MakeGridDH.F95
src/MakeGridDHC.F95
src/MakeGridGLQ.F95
src/MakeGridGLQC.F95
src/PreGLQ.f95
src/SHExpandDH.F95
src/SHExpandDHC.F95
src/SHExpandGLQ.F95
src/SHExpandGLQC.F95
src/SHExpandLSQ.F95

This mostly makes explicit things that are already done.
* REAL->INTEGER are cast with `int`
* INTEGER->INTEGER*1 are fixed by changing `phase` into a regular INTEGER. This is consistent with some other cases, though I don't know if it should be the other way. It would change the ABI though.
There are three lines with a COMPLEX->REAL conversion that are left, but I'm not sure what the correct fix is there.

Fix some conversion warnings

---

setup.py

That is, don't hard-code to Python 2, but use whatever was used to start pip/setup.py.

py3k: Use current Python interpreter to build docs.

---

MANIFEST.in
setup.py

This PR makes SHTOOLS pypi ready. It works on the testpypi server and can be installed with:
``` pip install -i https://testpypi.python.org/pypi pyshtools```
The version string needs to be improved because the direct git version fails for the pypi upload ...

Pypi fixes

---

examples/python/ClassInterface/exact_power.py
examples/python/ClassInterface/phaseonly.py
pyshtools/shclasses.py

This keyword for the ```from_random``` constructor allows to generate coefficients that have random phase but fixed amplitude:
```
clm = pyshtools.SHCoeffs.from_random(power, phaseonly=True)
```

phaseonly keyword

---

.travis.yml
Makefile
examples/notebooks/test_notebooks.py
examples/python/Common/FigStyle.py
examples/python/GravMag/TestGrav.py
examples/python/Makefile
pyshtools/shclasses.py

The following modifications have been made:
* The python notebooks are now run by a single python script `test_notebooks.py`, which reads the notebooks, and executes them. This file determines which version of python is being used, and executes the notebooks using that kernel. This is in contrast to the current situation that uses `make notebooks` and which tries to convert all notebooks to html.
* All python tests in `make python-tests-no-timing` are run. This does not run the timing/accuracy routines, which are computationally expensive.
The python tests are run using `Agg` by setting `export MPLBACKEND=Agg` in the travis script.
* In order to avoid installing `tex` on travis, I have commented out the line `'text.usetex': True` in the file `FigStyle.py.

Modify travis to run notebooks

---

pyshtools/make_docs.py
pyshtools/shclasses.py
src/pydoc/pymakegriddh.md

Thi pull request is largely cosmetic.
- Python documentation/docstrings were standardized by removing extra line breaks between parameters and headers. Docstrings in the shclasses.py were standardized to follow the conventions of the docstrings for other shtools functions. The class methods now explicitly define "returns", and each parameter starts with a line that describes the data type, and whether it is optional with a default value.
- Optional parametr `copy` was added to the docstrings, where needed.
- Added `copy=False` when initializing SHWindows from a cap or mask.
- Modified `SHCoeffs.get_coeffs` so that the default normalization and csphase correspond to the raw coefficients (and not 4pi and 1).
- Found some typos and missing aspects in the shclasses documentation.

Fix docstrings

---

Makefile
examples/fortran/Makefile
src/Makefile

Fix Makefile so that ifort invokes the preprocessor `-fpp` when compiling. Also add default option for openmp `-openmp`.

Fix makefiles so that ifort correctly invokes the preprocessor

---

Makefile
src/Makefile

Hi, these commits enable parallel build and flexible installation directory, and set PY3EXT to nopy3 if python3 is not found or abnormal.
Please review.
See PR #74.

Parallel build and flexible installation directory

---

pyshtools/shclasses/shwindow.py

The `SHWindow` methods `plot_windows()` and `plot_spectra()` would crash if the desired number of windows caused the number of rows in the plot to be equal to 1.

Fix SHWindow plotting routines (plot_spectra and plot_windows) when the number of rows is equal to 1

---

src/Wigner3j.f95

* This PR fixes a divide by zero in the routine Wigner3j that could cause a crash when compiled wit the option `-ffpe-trap=zero`. (Compilation with the default parameters seems to work fine.)
Thanks to @MikaelBeuthe for pointing this out.
Fixes #87

Reorder tests in conditional to avoid a divide by zero and crash when compiled with -ffpe-trap=zero

---

pyshtools/spectralanalysis/cross_spectrum.py

Without the optional argument "degrees" in cross_spectrum
degrees is set using numpy.range(lmax+1). However, this
is not a numpy function and 'nrange' should be used. This
patch makes cross_spectrum work as documented (i.e. without
the degrees argument) and matches the spectrum function.

Fix cross_spectrum without optional argument

---

.travis.yml
Makefile
pyshtools/shclasses/shcoeffsgrid.py
src/BAtoHilm.f95
src/BAtoHilmRhoH.f95
src/PythonWrapper.f95
src/pydoc/pybatohilmdh.md
src/pydoc/pybatohilmrhohdh.md
src/pydoc/pymakegriddh.md
src/pydoc/pymakegriddhc.md
src/pydoc/pyshread2error.md
src/pydoc/pyshreaderror.md
src/pydoc/pyshreaderrorh.md
src/pydoc/pyshreadh.md
src/pydoc/pyshreadjplerror.md

This pull request contains some minor improvements and bug fixes:
* Add optional argument `lmax` to `SHCoeffs.from_array()`.
* Zero pad coefficients when `lmax` is greater than the maximum degree in `SHCoeffs.to_array()`.
* Add method `pad()` to `SHCoeffs` class that zero pads or truncates the coefficients to a different `lmax`.
* Fix `SHCoeffs.from_file()` such that the maximum spherical harmonic degree of the class is the maximum spherical harmonic degree of the coeffs (and not lmaxin).
* Fix formatting issues with error messages in `SHCoeffs`.
* Remove print statements from fortran code in `BAtoHilm` and `BAtoHilmRohH` that served no purpose.
* Fix bug in the argument order of the python wrappers of `CilmPlusRhoDH` and `BAtoHilmRhoDH`.
* Fix `makefile` to remove `dist` directory during …

Minor changes before next release.

---

.travis.yml
setup.py

Enables autodetection of library locations. Numpy can correctly detect various BLAS/lapack locations automatically rather than having to hardcode them in setup.py. In addition, we upgrade conda's outdated MKL library because the autoconfiguration prefers MKL if it's found and the outdated version lacked routines that SHTOOLS needed.

[setup] autoconfigure libraries

---

setup.py

The default simply does nothing, so you could build and not link with the required libraries leaving the Python extensions broken.

Fail install if dependencies are not found.

---

pyshtools/shclasses/shcoeffsgrid.py
pyshtools/shclasses/shwindow.py

This PR adds support for plotting to an already existing figure by allowing the user to specify an existing matplotlib axes. 
Support has been added for the following methods:
* `SHCoeffs.plot_spectrum()`
* `SHCoeffs.plot_spectrum2d()`
* `SHGrid.plot()`
* `SHWindow.plot_windows()`
* `SHWindow.plot_spectra()`
* `SHWindow.plot_couplingmatrix()`
Support has not been added for `SHGrid.plot3d()`, as I can't figure out how to change the projection of an already existing axis (maybe this isn't possible?).
Here is an example of how to plot the power spectra and grid of a complex quantity on a single figure:
````
power = np.ones(100)
clm = pyshtools.SHCoeffs.from_random(power, kind="complex")
grid = clm.expand()
fig, axes = plt.subplots(2,2)
clm.plot_spectrum(ax=axes.flat[0]) …
```

Add support for plotting to an already existing figure

---

pyshtools/shclasses/shcoeffsgrid.py

The plot should only be shown when no ax is given

fixing bug in plot function

---

README.md
docs/pages/mydoc/gravity-magnetics.md
docs/pages/mydoc/implementation-details.md
docs/pages/mydoc/localized-spectral-analysis.md
docs/pages/mydoc/python-gravity-magnetics.md
docs/pages/mydoc/python-spectral-analysis.md
docs/pages/mydoc/release-notes-v3.md
docs/pages/mydoc/release-notes-v4.md

Hello :-)
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8) and Zenodo started using it for its badges as well. Accordingly, this PR updates all DOI links.
Cheers!

Hyperlink DOIs against preferred resolver

---

.travis.yml
docs/pages/mydoc/python-shgrid.md
pyshtools/shclasses/shcoeffsgrid.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shio/convert.py
setup.py

This PR adds support for saving gridded data in an `SHGrid` class instance to (1) netcdf and (2) xarray formats.
* `to_netcdf()` - export data to netcdf format. When saved to file, these can be used directly with GMT (generic mapping tools), where they are known as 'grd' files. 
* `to_xarray()` - export data to an xarray DataArray.

Add methods to_netcdf() and to_xarray() to the class SHGrid

---

README.md
docs/index.md
pyshtools/shclasses/shcoeffsgrid.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shmagcoeffs.py

Fix a small bug when rotating coefficients in the `SHCoeffs`, `SHMagCoeffs` and `SHGravCoeffs` classes when the input csphase is different from the default value.

Rotation bug fix

---

Contributors.txt
docs/pages/mydoc/contributors.md
docs/pages/mydoc/python-examples.md
docs/pages/mydoc/python-shcoeffs.md
docs/pages/mydoc/python-shgravcoeffs.md
docs/pages/mydoc/python-shgrid.md
docs/pages/mydoc/python-shmagcoeffs.md
pyshtools/shclasses/shcoeffsgrid.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shgravgrid.py
pyshtools/shclasses/shmagcoeffs.py
pyshtools/utils/figstyle.py

* Add the methods the methods `to_netcdf()` and `from_netcdf()` to the `SHGravCoeffs` and `SHMagCoeffs` classes.

netcdf support for gravity and magnetic field coeffiecients

---

.travis.yml
Makefile
README.md
docs/pages/fortran/fortran-installing.md
docs/pages/fortran/index-fortran.md
docs/pages/fortran/using-with-f95.md
docs/pages/mydoc/python-examples.md
environment.yml
fpm.toml
src/Makefile
src/fdoc/Makefile

This PR adds initial experimental support for fpm: the [fortran package manager](https://github.com/fortran-lang/fpm).
To install as a stand-alone project, it is only necesssary to use the command
```
fpm build
```
This will place the necessary .mod and .a files in a subdirectory of `build`.
To include shtools as a dependency in a project that compiles with fpm, you only need to add the following to the `fpm.toml` file:
```
[dependencies]
SHTOOLS = {git="https://github.com/SHTOOLS/SHTOOLS.git"}
```
Note that this feature is experimental. In the current state of fpm (which is undergoing active development), it is not possible to link to system wide libraries, such as fftw and lapack, which are required by shtools. This will hopefully be resolved …

Add initial support for fpm

---

Makefile
pyshtools/__init__.py
pyshtools/shclasses/shgeoid.py
pyshtools/shclasses/shgrid.py

This simple PR sets the gmt xarray accessor when exporting numpy grids to xarray.

Set xarray.gmt accessor for grids when pygmt is loaded

---

docs/Gemfile
docs/Gemfile.lock
docs/_config.yml
docs/_includes/sidebar.html
docs/pages/mydoc/python-datasets-constants.md
docs/pages/mydoc/python-shcoeffs.md
docs/pages/mydoc/python-shgravcoeffs.md
docs/pages/mydoc/python-shmagcoeffs.md
pyshtools/__init__.py
pyshtools/datasets/Earth/__init__.py
pyshtools/datasets/Mars.py
pyshtools/datasets/Mercury.py
pyshtools/datasets/Moon.py
pyshtools/datasets/Venus.py
pyshtools/shclasses/shcoeffs.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shgrid.py
pyshtools/shclasses/shmagcoeffs.py
pyshtools/shclasses/slepiancoeffs.py
pyshtools/utils/figstyle.py

* Add the method `admittance()`, `correlation()` and `admitcorr()` to `SHCoeffs`, `SHMagCoeffs` and `SHGravCoeffs` in order to compute the admittance and/or correlation with another function. Add the methods `plot_admittance()`, `plot_correlation()` and `plot_admitcorr()` to easily plot these functions.
* Add the boolean option `errors` to the method `to_array()` in order to control whether the error coefficients are returned with the function spherical harmonic coefficients.
* Add the lunar magnet field dataset of Ravat et al. (2020)
* Add the option `legend_loc` to most plotting routines to allow fine control over where the legend is placed.

Compute and plot the admittance and correlation

---

.travis.yml
Makefile
binder/environment.yml
docs/pages/fortran/fortran-examples.md
docs/pages/fortran/fortran-installing.md
docs/pages/fortran/index-fortran.md
docs/pages/mydoc/python-datasets-constants.md
docs/pages/mydoc/python-installing.md
environment.yml
pyshtools/constants/__init__.py
requirements-dev.txt
requirements.txt
setup.py
src/SHTOOLS.f95
src/fdoc/shmagpowerl.md
src/fdoc/shmagpowerspectrum.md
src/fdoc/shmultiply.md
src/fdoc/shmultitapermaskcse.md
src/fdoc/shmultitapermaskse.md
src/fdoc/shmultitaperse.md
src/fdoc/slepiancoeffs.md
src/fdoc/slepiancoeffstosh.md

Update binder environment.
In addition, the `SHTOOLS.f95` and fortran documentation have been modified to use a systematic "cilm" nomenclature for spherical harmonic variables. However, the original source code of these functions has not (yet) been updated to reflect these changes. This should pose no problems as none of these variables are optional.
These subroutines should eventually update the variable names to the new consistent nomenclature
```
SHPowerL
SHPowerDensityL
SHCrossPowerL
SHCrossPowerDensityL
SHPowerSpectrum
SHPowerSpectrumDensity
SHCrossPowerSpectrum
SHCrossPowerSpectrumDensity
SHPowerLC
SHPowerDensityLC
SHPowerDensityLC
SHCrossPowerLC
SHCrossPowerDensityLC
SHPowerSpectrumC
SHPowerSpectrumDensityC
SHCrossPowerSpectrumDensityC
SHAdmitCorr
SHLocalizedAdmitCorr …
```

update binder dependecies

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/release_checklist.md
.github/pull_request_template.md
.travis.yml
AUTHORS.md
Makefile
README.md
binder/environment.yml
docs/pages/fortran/fortran-contributors.md
docs/pages/mydoc/contributors.md
docs/pages/mydoc/python-installing.md
environment.yml
examples/fortran/Makefile
pyshtools/shclasses/shgrid.py
requirements-dev.txt
src/Makefile

Version 4.7.1
This maintenance release updates the makefiles so that they can be used correctly with homebrew-core and macports.
* Relative paths are removed in a few cases by explicitly passing variables such as `$(MODPATH)$` to all dependent sub-makefiles.
* Default variables are no longer set in the sub-makefiles, as these are not intended to be used independently. All variables are passed directly from the main Makefile.
* Renamed the directory `modules` to `include` to be consistent with macports and homebrew installations.
* The F95FLAGS are set by searching if the compiler name contains the "short" compiler name. This allows recognizing "gfortran-10" as being "gfortran".
* Added a `.github` folder with templates for issues and releases checklists.
* Converted matplotlib relative …

v4.7.1 maintenance release

---

.github/ISSUE_TEMPLATE/release_checklist.md
.travis.yml
environment.yml

remove python version from environment.yml, and then specify this manually when creating the build matrix in Travis.

Update travis build and conda environment

---

Makefile
docs/pages/mydoc/faq.md
environment.yml
examples/notebooks/grids-and-coefficients.ipynb
pyshtools/constants/Venus.py
pyshtools/datasets/Ceres.py
pyshtools/datasets/Earth/Earth2012/__init__.py
pyshtools/datasets/Earth/__init__.py
pyshtools/datasets/Mars.py
pyshtools/datasets/Mercury.py
pyshtools/datasets/Moon.py
pyshtools/datasets/Venus.py
pyshtools/datasets/Vesta.py
pyshtools/shclasses/shcoeffs.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shgrid.py
pyshtools/shclasses/shmagcoeffs.py
pyshtools/shio/dov.py
pyshtools/shio/icgem.py
pyshtools/shio/read_igrf.py
pyshtools/shio/shtools.py
requirements.txt
setup.py

* Update `makefile install` to include example data files, and to place in the correct directories for homebrew.
* Update dependencies, including `astropy>=4.0`.
* Add the option `encoding` for all routines and methods that read or write text-based spherical harmonic files.
* Hard coded all datasets to use `utf-8` in order to avoid problems with the XGM2019E dataset that has a character that can not be decoded by the GBK encoding that is the default in some Chinese installations.
* Update Venus rotation period using data from Margot et al. (2021).

Various updates

---

pyshtools/shclasses/shgrid.py
src/SHExpandDHC.f95

This PR fixes 2 bugs related to complex spherical harmonic transforms.
The first regards the Fortran routine `SHExpandDHC` and hence affects both shtools and pyshtools. For complex grids, the **last** coefficient `coeffs[1, lmax, lmax]` was in error only when `lmax` was odd. The origin of this is a missing (-1)^m factor that should have been applied to a term.
The second regards the `SHGrid.expand()` routine for complex data with grid type `DH2`. The origin of this error is that the parameter `sampling=2` was not passed to the Fortran routine. The spherical harmonic coefficients for this case were all wrong, and this should have been obvious by simple inspection.
Fixes: https://github.com/SHTOOLS/SHTOOLS/issues/300

Fix 2 bugs with complex spherical harmonic transforms

---

pyshtools/shclasses/shgravcoeffs.py
pyshtools/shio/icgem.py

This PR improves the reading of ICGEM formatted files of gravitational potential models:
* The time variable contribution was not computed when the coefficients had an associated `trnd` or `dot` term. This was because each `d` was replaced with an `e` for compatibility when parsing floating point numbers, but this modified the key of the line, which was then not recognized and ignored. This has been fixed by not making the string replacement for the first entry.
* When a line in the data section starts with an unknown key, a warning is printed to the screen, informing that the line will be ignored. This warning can be turned off by specifying `quiet=True`.
* For files formatted as `icgem2.0`, time variable terms were simply ignored if the specified epoch fell outside of the allowed range. …

Improve the reading of ICGEM formatted files

---

pyshtools/shclasses/shgrid.py

Hi !
I just encountered a small bug in the python code, so I wrote a simple fix, if you want to merge it
Basically on rare cases, in `shgrid.from_cap`, when calculating `dist`, floating-point calculation errors could give a result slightly superior to 1 (I had `1.0000000000000002`). In that case, the `arccos` at the following line will output `NaN`, and may raise an exception (if `numpy` is configured to do so, see [numpy.seterr](https://numpy.org/doc/stable/reference/generated/numpy.seterr.html) ).
So what I did was cap that value to `1.` (see the changelog)

patched a floating point error-caused bug (arccos of value >= 1)

---

pyshtools/shclasses/shcoeffs.py
src/MakeGradientDH.f95
src/PythonWrapper.f95
src/SHTOOLS.f95
src/fdoc/makegradientdh.md
src/pydoc/pymakegradientdh.md
src/pyshtools.pyf

The default behavior of the Fortran routine MakeGradientDH and the python `SHCoeffs` method `gradient` has been modified. The original behavior was to compute the gradient on a sphere of radius `r`, where `r` was the degree 0 coeffieicient of the function. Though this makes sense for some functions (such as planetary topography), this is not useful for other functions (such as temperature).
The new behaviour is to compute the gradient on the unit sphere (r=1). This radius can be modified by supplying the optional argument `radius`.
The gradient function was introduced in v4.8 about 1 year ago.

Change default behavior of MakeGradientDH and SHCoeffs.gradient

---

docs/pages/mydoc/python-installing.md
environment.yml
pyshtools/backends/__init__.py
pyshtools/backends/backends.py
pyshtools/backends/ducc0_wrapper.py

* moved the ducc0_wrapper.py file to the backends module.
* use conda version of ducc0 in environment.yml. 
* Minor documentation changes

move wrapper functions to backends module

---

docs/pages/mydoc/complex-spherical-harmonics.md

Missing differential of mu in orthogonality property of Associated Legendre polynomials in complex spherical harmonic documentation page.
**Reminders**

Missing Differential of mu

---

docs/pages/mydoc/backends.md
docs/pages/mydoc/release-notes-v4.md
environment-dev.yml
pyshtools/backends/__init__.py
pyshtools/backends/backends.py

ducc was set as the default backend in a previous PR, but this PR improves the handling of the case where ducc0 is not installed.

Make ducc the default backend

---

docs/Gemfile
docs/Gemfile.lock
docs/_data/sidebars/fortran_sidebar.yml
docs/_data/sidebars/mydoc_sidebar.yml
docs/pages/fortran/fortran-chat.md
docs/pages/fortran/fortran-release-notes-v4.md
docs/pages/mydoc/chat.md
docs/pages/mydoc/release-notes-v4.md
examples/python/ClassInterface/ClassExample.py
examples/python/ClassInterface/WindowExample.py
examples/python/ClassInterface/exact_power.py
examples/python/GlobalSpectralAnalysis/GlobalSpectralAnalysis.py
examples/python/GravMag/TestCT.py
examples/python/GravMag/TestGrav.py
examples/python/IOStorageConversions/SHConversions.py
examples/python/IOStorageConversions/SHStorage.py
examples/python/LocalizedSpectralAnalysis/SHMTCouplingMatrix.py
examples/python/LocalizedSpectralAnalysis/SHMultitaperSE.py
examples/python/LocalizedSpectralAnalysis/SHWindowsBiasOther.py
examples/python/Other/TestOther.py
examples/python/SHRotations/SHRotations.py
examples/python/TestLegendre/TestLegendre.py
examples/python/TimingAccuracy/TimingAccuracyDH.py
examples/python/TimingAccuracy/TimingAccuracyDHC.py
examples/python/TimingAccuracy/TimingAccuracyGLQ.py
examples/python/TimingAccuracy/TimingAccuracyGLQC.py
examples/python/ducctest.py

* Update web documentation.
* Update python examples so that they don't call routines directly in the shtools backend.
Note: The module `pyshtools.shtools` will be deprecated in the v4.11 release. This module represents 1 of 2 possible backends for pyshtools, and will henceforth be located at `pyshtools.backends.shtools`. Unless explicitly required, the user should avoid using the `backends` modules directly, and should instead call the routines that are located in the top level modules such as `pyshtools.expand`. Setting the backend by use of the routine `pyshtools.backends.selected_preferred_backend()` determines which backed to use when calling the routines in the top level modules.

Update web documentation

---

setup.py

The PR fixes `setup.py` to work with all versions of setuptools. In a previous commit, we fixed this to work with setuptools=62.1.0, but this was not backwards compatible. This change checks for the version of setuptools and then formats the build directory accordingly.
**Reminders**

Fix setup.py to work with setuptools newer and older than 62.1.0

---

pyshtools/shclasses/shcoeffs.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shmagcoeffs.py

Dear colleague,
This is a minor change (3 characters), to fix this error I had:
```
>>> import pyshtools as pysh
>>> hlm = pysh.datasets.Venus.VenusTopo719()
>>> hlm.set_coeffs(ls=2, ms=0, values=0.)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "[...]/lib/python3.8/site-packages/pyshtools/shclasses/shcoeffs.py", line 962, in set_coeffs
mneg_mask = (ms < 0).astype(_np.int)
File "[...]/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
```
This error appears for the latest numpy release, I traced it back to [this numpy deprecation](https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is …

fix_np_types

---

setup.py

While trying to [fix the conda recipe for arm64](https://github.com/conda-forge/pyshtools-feedstock/pull/37), I ran into an issue for all platforms with updated setuptools versions.
`setup.py` was previously relying on `pkg_resources` being imported from `setuptools`. That broke in
https://github.com/pypa/setuptools/commit/6050634818943befefe3a85a12503b6d8a1e8106
**Reminders**

fix import of pkg_resources

---

examples/cpp/test.cpp
examples/fortran/MarsCrustalThickness/MarsCrustalThickness.f95
examples/fortran/SHCilmPlus/TestCilmPlus.f95
examples/fortran/SHExpandDH/TestExpandDH.f95
examples/fortran/SHExpandLSQ/TestSHExpandLSQ.f95
examples/fortran/SHLocalizedAdmitCorr/LocalizedAdmitCorr.f95
examples/fortran/SHMag/SHMag.f95
examples/fortran/SHRotate/TestSHRotate.f95

When building with Meson, the build will _always_ be in an out-of-source build directory, so tests cannot rely on relative paths like these do to find their data.
This PR reads the data path from the command line, which allows testing from any build directory, no matter where it is, as the path to the source directory can be passed.
I also had to modify the an additional input file to some of the Fortran tests, in order to supply test options directly, instead of as data on standard input.
**Reminders**

Allow passing test input data from command line

---

pyshtools/doc/make_docs.py
src/create_c_header.py
src/create_cbind_wrapper.py
src/fdoc/make_www_doc.py
src/pydoc/make_www_doc.py

This prevents several invalid escape warnings, and though it isn't necessary if there aren't any backslashes in the string, it's easier to be consistent about it.
**Reminders**

Use raw strings for regex

---

pyshtools/datasets/Earth/Earth2012/__init__.py
pyshtools/datasets/Earth/Earth2014/__init__.py

Update the URLs for the Earth2012/2014 datasets. Curtin appears to have changed the folder name where these are located from "gravitymodels" to just "models".

Update url for Earth2012/2014 datasets

---

pyshtools/backends/shtools.py

Currently, docs for wrapped subroutines start with:
```
Help on function wrapped_func in module pyshtools.backends.shtools:
wrapped_func(*args, **kwargs)
```
This is because only `__doc__` is copied, but not the `__name__` and other special properties. Using `functools.wraps` copies all important properties, and changes the docs to:
```
Help on function BAtoHilmDH in module pyshtools.backends.shtools:
BAtoHilmDH(...)
```
But note there needs to be a small tweak to `__name__` because f2py adds an extra 'function ' prefix to the name.
**Reminders**

Fix wrapping of Fortran subroutines

---

pyshtools/shclasses/shcoeffs.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shmagcoeffs.py
src/SHExpandLSQ.F95

* Fix a problem with `SHCoeffs.volume()` when the normalization is `ortho`.
* Fix a potential LAPACK underscore problem when compiling with `LAPACK_UNDERSCORE` specified.
* Minor changes for Numpy 2 compatibility.
**Reminders**

Fix shcoeffs.volume for ortho, fix LAPACK underscore issue + numpy2

---

.github/workflows/pypi_publish.yml

Version 4.11.2

---

.github/workflows/pypi_publish.yml

Version 4.11.3

---

.github/workflows/pypi_publish.yml

Version 4.11.4

---

.github/workflows/pypi_publish.yml

Version 4.11.5

---

.github/workflows/pypi_publish.yml

Version 4.11.6

---

.github/workflows/pypi_publish.yml

Version 4.11.7

---

.github/workflows/pypi_publish.yml
pyproject.toml

Version 4.11.8

---

docs/pages/mydoc/python-installing.md
pyproject.toml

Latest Cartopy produces wheels, so there's no need to install its build-time dependencies ourselves.
**Reminders**

Remove Cartopy build-time dependencies

---

pyshtools/shclasses/shcoeffs.py
pyshtools/shclasses/shgeoid.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shgrid.py
pyshtools/shclasses/shmagcoeffs.py
pyshtools/shio/bshc.py
pyshtools/shio/dov.py
pyshtools/shio/icgem.py
pyshtools/shio/read_igrf.py
pyshtools/shio/shtools.py

With this change you can pass `pathlib.Path` to `shread` and other input/output functions, including `SHCoeffs.to/from_file`, `SHGravCoeffs.to/from_file` and `SHMagCoeffs.to/from_file`.

Add pathlib support to input and output

---

.github/workflows/pypi_publish.yml
docs/pages/mydoc/python-datasets-constants.md

**New Datasets!**
* Added new ultra-high degree shape models of the Moon in both principal axis and mean Earth/polar axis coordinate systems (LOLA_shape and LOLA_shape_pa) and moved MoonTopo2600p to historical.
* Added new ultra-high degree shape model of Mars (MOLA_shape) and moved MarsTopo2600 and MarsTopo719 to historical.
* Added a new ultra-high degree shape model of Mercury based on the USGS SPG DTM (USGS_SPG_shape).
* Added a new ultra-high degree shape model of Vesta based on the DLR SPG DTM (DLR_SPG_shape).
* Added a new ultra-high degree shape model of Ceres based on the DLR SPG DTM (DLR_SPG_shape) and a high-degree shape model based on the JPL SPC DTM (JPL_SPG_shape).
* Added historical degree-2 gravity models of Io, Europa, Ganymede, and Callisto derived from data collected by …

Version 4.12.1

---

examples/cpp/meson.build
examples/meson.build

**New Datasets!**
* Added new ultra-high degree shape models of the Moon in both principal axis and mean Earth/polar axis coordinate systems (LOLA_shape and LOLA_shape_pa) and moved MoonTopo2600p to historical.
* Added new ultra-high degree shape model of Mars (MOLA_shape) and moved MarsTopo2600 and MarsTopo719 to historical.
* Added a new ultra-high degree shape model of Mercury based on the USGS SPG DTM (USGS_SPG_shape).
* Added a new ultra-high degree shape model of Vesta based on the DLR SPG DTM (DLR_SPG_shape).
* Added a new ultra-high degree shape model of Ceres based on the DLR SPG DTM (DLR_SPG_shape) and a high-degree shape model based on the JPL SPC DTM (JPL_SPG_shape).
* Added historical degree-2 gravity models of Io, Europa, Ganymede, and Callisto derived from data collected by …

Version 4.12.2

---

pyproject.toml
pyshtools/backends/ducc0_wrapper.py
pyshtools/shclasses/shcoeffs.py
pyshtools/shclasses/shgeoid.py
pyshtools/shclasses/shgradient.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shgravgrid.py
pyshtools/shclasses/shgrid.py
pyshtools/shclasses/shmagcoeffs.py
pyshtools/shclasses/shmaggrid.py
pyshtools/shclasses/shtensor.py
pyshtools/shclasses/shwindow.py
pyshtools/shclasses/slepian.py
pyshtools/shclasses/slepiancoeffs.py
pyshtools/shio/convert.py
pyshtools/shio/dov.py
pyshtools/shio/shtools.py

* Use `isinstance` when comparing types.
* Use `except Exception` to avoid bare except.
* Improve `setuptools_scm` version detection when working with non-git-versioned projects.
* Improve handling of the class attribute `name`. This attribute was added to classes that did not define name, and every method that returns a class instance now has the ability to set the name of the new instance. When creating grids from coefficients, the name of the grid class is inherited from the name of the coefficient class.
* Add the option to rotate the ellipoid generated by `SHGrid.from_ellipsoid()` about the z axis by the angle `alpha`.

Fix type comparisons and bare except

---

pyshtools/doc/normalgravity.doc
src/NormalGravity.f95
src/fdoc/normalgravity.md
src/pydoc/pynormalgravity.md

This PR changes the way that the normal gravity is computed when the reference ellipsoid is a sphere. 
The normal gravity is defined as the magnitude of the total gravity (gravitation + centrifugal) on the surface. In contrast to the case of an ellipsoid, the surface of the sphere does not correspond to an equipotential surface, and the gravity vector is not normal to the surface. See https://www.fatiando.org/boule/latest/api/generated/boule.Sphere.html#boule.Sphere.normal_gravity

Better normal gravity on a sphere

---

pyshtools/shclasses/shcoeffs.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shgrid.py
pyshtools/shclasses/shmagcoeffs.py

This API was deprecated in Matplotlib 3.7 and will be removed for 3.9.
**Reminders**

Stop using deprecated Matplotlib API

---

docs/pages/mydoc/python-datasets.md
pyshtools/datasets/Moon/__init__.py
pyshtools/datasets/Moon/historical/shape.py
src/PlmBar.f95
src/PlmBar_d1.f95
src/PlmON.f95
src/PlmON_d1.f95
src/PlmSchmidt.f95
src/PlmSchmidt_d1.f95

* Add the LDEM_pa ultrahigh degree shape model of the Moon (11519) to the datasets module, and move the previous LOLA_pa shape model to historical.
**Reminders**

Add new LDEM_pa shape model for the Moon

---

docs/pages/fortran/fortran-complex-spherical-harmonics.md
docs/pages/fortran/fortran-real-spherical-harmonics.md
docs/pages/mydoc/complex-spherical-harmonics.md
docs/pages/mydoc/python-shcoeffs.md
docs/pages/mydoc/python-shgravcoeffs.md
docs/pages/mydoc/python-shmagcoeffs.md
docs/pages/mydoc/real-spherical-harmonics.md
pyshtools/shclasses/shcoeffs.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shmagcoeffs.py

Hi!
Noticed some inconsistencies in the documentation for either excluding or applying the csphase. Specifically:
- some parts of the docs say, respectively, (0) and (1)
- some say respectively (-1) and (1)
- and others say what I believe to be correct, respectively (1) and (-1). Please let me know if I misunderstood or missed anything.
Otherwise, the changes below should fix that.
(and minor change : the `epoch` entry was listed twice in the docs for [SHGravCoeffs class](https://shtools.github.io/SHTOOLS/python-shgravcoeffs.html))
Best regards,
PL
**Reminders**
- [ n/a] If adding new features, update the docstring to provide all information that is required to use the feature.

in docs : fix inconsistencies in for csphase values

---

.github/workflows/build_wheels.yml
.github/workflows/ci_test.yml
Makefile
docs/pages/fortran/fortran-95-problems.md
docs/pages/fortran/fortran-installing.md
docs/pages/fortran/using-with-f95.md
docs/pages/mydoc/python-datasets.md
pyshtools/datasets/Moon/__init__.py
pyshtools/shclasses/shcoeffs.py
pyshtools/shclasses/shgravcoeffs.py
pyshtools/shclasses/shmagcoeffs.py
pyshtools/spectralanalysis/cross_spectrum.py
pyshtools/spectralanalysis/spectrum.py

* Update cibuildwheels version and stop using Mamba: see #494 
* Add the GL1800F lunar gravity model to the datasets module.
* Remove the `-m64` compiler flag that gives rise to incompatibilites with aarch64 platforms, and which probably is no longer necessary: see #507 
* Fix inconsistency with how the (cross-)spectrum is computed when using the option `l2norm`. See #506 
* Fix a bug where the optional parameter `lmax` was not treated properly for `SHCoeffs.expand()` when using `GLQ` grids with the `shtools` backend.

Development updates

---

pyshtools/backends/ducc0_wrapper.py
pyshtools/shclasses/shcoeffs.py

This hopefully fixes the incorrect handling of `lmax` in the `MakeGrid` routines of the `ducc` backend.
**Reminders**

Fix issue #510
